### ISSUE TITLE
Festhängender Arm

### ISSUE THREAD

**Issue by NoDruid** [NoDruid/Zerblobben-Blobbageddon#1]
Arm bleibt am Boden hängen nachdem man sich nach vorne ziehen will und lässt sich nicht mehr lösen auch nach mehrfachen drücken des Greifbuttons.

**Comment by Kezzo** [comment]
Issue closed durch Änderung der Bedingung wann losgelassen wird. Ist jetzt genereller, da man davon ausgehen kann, dass der Spieler loslassen möchte wenn vom Trigger ButtonUp gecalled wird und er kein Item in der Hand hält.
Wenns nochmal vorkommt, bitte Issue wieder öffnen mit Beschreibung wann genau es passierte.
