### ISSUE TITLE
Protoguns funktionieren nur an einer Hand

### ISSUE THREAD

**Issue by NoDruid** [NoDruid/Zerblobben-Blobbageddon#2]
Protoguns funktionieren nur an der rechten oder der linken Hand, man kann die Hände also nicht wechseln.

**Comment by Fabdedudel** [comment]
Das is nicht direkt der Fehler, man kann die Waffen zwischen Händen Tauschen, hab aber gesehen, was du meinst, ab und zu gibt das Probleme und man kann die Waffe insgesamt nicht mehr benutzen. Könnte daran liegen, das die Waffe zwischendurch im Inventar hängt. Und da was falsch eingestellt wird.

**Comment by Kezzo** [comment]
Issue **vorzeitig** closed durch Überarbeitung des setzen der Layer bei Items.
