### ISSUE TITLE
Usable items zielen nicht nach vorne

### ISSUE THREAD

**Issue by Fabdedudel** [NoDruid/Zerblobben-Blobbageddon#3]
Durch das aufheben drehen sich items in HydraRotation richtung, nicht in Spielerrichtung, müsste easy zu fixen sein

**Comment by Kezzo** [comment]
Issue closed durch ausrichtung der Waffe nach den Targets, da es sonst zu Child-Parent-Problemen kommen könnte, keine sonstige Einschränkung
